# Data Preperation

How does the data look like?

In [21]:
# Make sure to pip install openpyxl before reading excel files

In [2]:
import pandas as pd

In [ ]:
DATA_PATH = 'Muesli Project raw data.xlsx'
orders = pd.read_excel(DATA_PATH, sheet_name='Orders')

# rename columns in the dateset 

# get columns names from the first row 
col_names = list(orders.iloc[0])

# assign the columns names the right name
orders.columns = col_names
orders = orders[1:]

orders.head(5)

,Index,Order ID,Order Date,Ship Mode,Customer ID,Customer Name,Origin Channel,Country/Region,City,State,Postal Code,Region,Category,Sub-Category,Product ID,Sales,Quantity,Discount,Profit
1,27,CA-2019-121755,2019-01-16 00:00:00,Second Class,EH-13945,Eric Hoffmann,Email,United States,Los Angeles,California,90049,West,Special Projects Muesil,Gluten Free,TEC-AC-10003027,90.57,3,0,11.7741
2,45,CA-2019-118255,2019-03-11 00:00:00,First Class,ON-18715,Odella Nelson,Sales,United States,Eagan,Minnesota,55122,Central,Special Projects Muesil,Gluten Free,TEC-AC-10000171,45.98,2,0,19.7714
3,48,CA-2019-169194,2019-06-20 00:00:00,Standard Class,LH-16900,Lena Hernandez,Email,United States,Dover,Delaware,19901,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,45,3,0,4.95
4,60,CA-2019-111682,2019-06-17 00:00:00,First Class,TB-21055,Ted Butterfield,Email,United States,Troy,New York,12180,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,30,2,0,3.3
5,63,CA-2018-135545,2018-11-24 00:00:00,Standard Class,KM-16720,Kunst Miller,Email,United States,Los Angeles,California,90004,West,Special Projects Muesil,Gluten Free,TEC-AC-10004633,13.98,2,0,6.1512

In [12]:
orders.shape

(9994, 19)

In [ ]:
campaign_data = pd.read_excel(DATA_PATH, sheet_name='Campaign Data')
campaign_data.head(5)

         Order ID Arrival Scan Date     Customer Name
0  CA-2019-109666        2019-05-03      Kunst Miller
1  CA-2019-138933        2019-05-03       Jack Lebron
2  CA-2019-130001        2019-05-03  Heather Kirkland
3  CA-2019-113061        2019-05-06         Ed Ludwig
4  CA-2019-162138        2019-05-06       Grace Kelly

In [17]:
campaign_data.shape

(333, 3)

In [ ]:
order_process = pd.read_excel(DATA_PATH, sheet_name='Order Process Data')
order_process.head(5)

   Row ID        Order ID Order Date On Truck Scan Date            Ship Mode
0    3074  CA-2019-125206 2019-01-03         2019-01-07              Express
1    4919  CA-2019-160304 2019-01-02         2019-01-09  Standard Processing
2    4920  CA-2019-160304 2019-01-02         2019-01-09  Standard Processing
3    8604  US-2019-116365 2019-01-03         2019-01-09  Standard Processing
4    8605  US-2019-116365 2019-01-03         2019-01-09  Standard Processing

In [ ]:
intern_data = pd.read_excel(DATA_PATH, sheet_name='InternData Study')
intern_data.head(5)

         Order ID Ready to Ship Date Pickup Date
0  CA-2019-116540         2019-09-02  2019-09-03
1  CA-2019-116540         2019-09-02  2019-09-03
2  CA-2019-129847         2019-09-04  2019-09-04
3  CA-2019-129630         2019-09-04  2019-09-04
4  CA-2019-106278         2019-09-05  2019-09-06

## Orders

In [ ]:
# Reset the Index
orders.drop(columns='Index', inplace=True)

,Order ID,Order Date,Ship Mode,Customer ID,Customer Name,Origin Channel,Country/Region,City,State,Postal Code,Region,Category,Sub-Category,Product ID,Sales,Quantity,Discount,Profit
1,CA-2019-121755,2019-01-16 00:00:00,Second Class,EH-13945,Eric Hoffmann,Email,United States,Los Angeles,California,90049,West,Special Projects Muesil,Gluten Free,TEC-AC-10003027,90.57,3,0,11.7741
2,CA-2019-118255,2019-03-11 00:00:00,First Class,ON-18715,Odella Nelson,Sales,United States,Eagan,Minnesota,55122,Central,Special Projects Muesil,Gluten Free,TEC-AC-10000171,45.98,2,0,19.7714
3,CA-2019-169194,2019-06-20 00:00:00,Standard Class,LH-16900,Lena Hernandez,Email,United States,Dover,Delaware,19901,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,45,3,0,4.95
4,CA-2019-111682,2019-06-17 00:00:00,First Class,TB-21055,Ted Butterfield,Email,United States,Troy,New York,12180,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,30,2,0,3.3
5,CA-2018-135545,2018-11-24 00:00:00,Standard Class,KM-16720,Kunst Miller,Email,United States,Los Angeles,California,90004,West,Special Projects Muesil,Gluten Free,TEC-AC-10004633,13.98,2,0,6.1512
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9990,US-2019-115441,2019-07-25 00:00:00,Second Class,SH-19975,Sally Hughsby,Sales,United States,Milwaukee,Wisconsin,53209,Central,Toasted Muesli,With Nuts,FUR-CH-10004626,403.56,4,0,96.8544
9991,US-2018-129007,2018-09-13 00:00:00,First Class,KD-16615,Ken Dana,Sales,United States,Anaheim,California,92804,West,Toasted Muesli,With Nuts,FUR-CH-10000155,717.72,3,0.2,71.772
9992,CA-2018-132388,2018-10-10 00:00:00,First Class,KN-16390,Katherine Nockton,Sales,United States,Santa Barbara,California,93101,West,Toasted Muesli,With Nuts,FUR-CH-10001714,362.136,3,0.2,-54.3204
9993,CA-2019-149272,2019-03-15 00:00:00,Standard Class,MY-18295,Muhammed Yedwab,Sales,United States,Bryan,Texas,77803,Central,Toasted Muesli,With Nuts,FUR-CH-10000863,528.43,5,0.3,-143.431
9994,CA-2020-121559,2020-06-01 00:00:00,Second Class,HW-14935,Helen Wasserman,Sales,United States,Indianapolis,Indiana,46203,Central,Toasted Muesli,With Nuts,FUR-CH-10003746,1925.88,6,0,539.2464