In [40]:
import pandas as pd

# Orders

In [41]:
orders = pd.read_excel('C:/Users/rizza/Desktop/gaussian_peppers/m2-pandas/muesli-project/Muesli Project raw data.xlsx', sheet_name='Orders')
new_header= orders.iloc[0]
orders = orders[1:]
orders.columns=new_header
orders["Order ID"] = orders["Order ID"].astype(str).str.strip()
orders["Order Date"] = pd.to_datetime(orders["Order Date"], errors="coerce")


# there is an empty row at the top. the actual index is in the first row

In [42]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 1 to 9994
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Index           9994 non-null   object
 1   Order ID        9994 non-null   object
 2   Order Date      9994 non-null   datetime64[ns]
 3   Ship Mode       9994 non-null   object
 4   Customer ID     9994 non-null   object
 5   Customer Name   9994 non-null   object
 6   Origin Channel  9994 non-null   object
 7   Country/Region  9994 non-null   object
 8   City            9994 non-null   object
 9   State           9994 non-null   object
 10  Postal Code     9983 non-null   object
 11  Region          9994 non-null   object
 12  Category        9994 non-null   object
 13  Sub-Category    9994 non-null   object
 14  Product ID      9994 non-null   object
 15  Sales           9994 non-null   object
 16  Quantity        9994 non-null   object
 17  Discount        9994 non-null   object
 18  Profit          9994 non-null   object
dtypes: datetime64[ns](1), object(18)
memory usage: 1.4+ MB

In [53]:
orders.describe()

0                         Order Date
count                           9994
mean   2019-04-30 17:41:20.448269312
min              2017-01-03 00:00:00
25%              2018-05-23 00:00:00
50%              2019-06-26 00:00:00
75%              2020-05-14 00:00:00
max              2020-12-30 00:00:00

In [43]:
print(df.columns.tolist())

['Index', 'Order ID', 'Order Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Origin Channel', 'Country/Region', 'City', 'State', 'Postal Code', 'Region', 'Category', 'Sub-Category', 'Product ID', 'Sales', 'Quantity', 'Discount', 'Profit']

# Order Process Table 1

In [44]:
order_process = pd.read_excel('C:/Users/rizza/Desktop/gaussian_peppers/m2-pandas/muesli-project/Muesli Project raw data.xlsx', sheet_name='Order Process Data')
order_process["Order ID"] = order_process["Order ID"].astype(str).str.strip()
order_process["On Truck Scan Date"] = pd.to_datetime(order_process["On Truck Scan Date"], errors="coerce")


# file contains 3 empty columns

In [45]:
order_process.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5899 entries, 0 to 5898
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Row ID              5899 non-null   int64
 1   Order ID            5899 non-null   object
 2   Order Date          5899 non-null   datetime64[ns]
 3   On Truck Scan Date  5899 non-null   datetime64[ns]
 4   Ship Mode           5899 non-null   object
dtypes: datetime64[ns](2), int64(1), object(2)
memory usage: 230.6+ KB

In [54]:
order_process.describe()

,Row ID,Order Date,On Truck Scan Date
count,5899.000000,5899,5899
mean,5022.428208,2020-02-29 02:22:48.231903744,2020-03-06 05:16:21.929140480
min,1.000000,2019-01-02 00:00:00,2019-01-07 00:00:00
25%,2485.500000,2019-09-11 00:00:00,2019-09-18 00:00:00
50%,5091.000000,2020-03-16 00:00:00,2020-03-20 00:00:00
75%,7460.000000,2020-09-13 12:00:00,2020-09-18 00:00:00
max,9994.000000,2020-12-30 00:00:00,2021-01-06 00:00:00
std,2878.464633,NaN,NaN

# Campaign Data Table 1

In [46]:
campaign = pd.read_excel('C:/Users/rizza/Desktop/gaussian_peppers/m2-pandas/muesli-project/Muesli Project raw data.xlsx', sheet_name='Campaign Data')

In [47]:
campaign["Order ID"] = campaign["Order ID"].astype(str).str.strip()
campaign["Arrival Scan Date"] = pd.to_datetime(campaign["Arrival Scan Date"], errors="coerce")

In [48]:
campaign.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 333 entries, 0 to 332
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Order ID           333 non-null    object
 1   Arrival Scan Date  333 non-null    datetime64[ns]
 2   Customer Name      333 non-null    object
dtypes: datetime64[ns](1), object(2)
memory usage: 7.9+ KB

# Inter Data Study

In [49]:
intern_data = pd.read_excel('C:/Users/rizza/Desktop/gaussian_peppers/m2-pandas/muesli-project/Muesli Project raw data.xlsx', sheet_name='InternData Study')
intern_data["Order ID"] = intern_data["Order ID"].astype(str).str.strip()
intern_data["Ready to Ship Date"] = pd.to_datetime(intern_data["Ready to Ship Date"], errors="coerce")
intern_data["Pickup Date"] = pd.to_datetime(intern_data["Pickup Date"], errors="coerce")

In [50]:
intern_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 290 entries, 0 to 289
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Order ID            290 non-null    object
 1   Ready to Ship Date  290 non-null    datetime64[ns]
 2   Pickup Date         290 non-null    datetime64[ns]
dtypes: datetime64[ns](2), object(1)
memory usage: 6.9+ KB

# Matching Data from Order IDs

In [51]:
merged = pd.merge(orders, campaign[["Order ID", "Arrival Scan Date"]], on="Order ID", how="left")
merged = pd.merge(merged, order_process[["Order ID", "On Truck Scan Date"]], on="Order ID", how="left")
merged = pd.merge(merged,intern_data[["Order ID", "Ready to Ship Date", "Pickup Date"]],on="Order ID",how="left")
merged = merged.set_index("Order ID")
merged.head()

,Index,Order Date,Ship Mode,Customer ID,Customer Name,Origin Channel,Country/Region,City,State,Postal Code,...,Sub-Category,Product ID,Sales,Quantity,Discount,Profit,Arrival Scan Date,On Truck Scan Date,Ready to Ship Date,Pickup Date
Order ID,,,,,,,,,,,,,,,,,,,,,
CA-2019-121755,27,2019-01-16,Second Class,EH-13945,Eric Hoffmann,Email,United States,Los Angeles,California,90049,...,Gluten Free,TEC-AC-10003027,90.57,3,0,11.7741,NaT,2019-01-23,NaT,NaT
CA-2019-121755,27,2019-01-16,Second Class,EH-13945,Eric Hoffmann,Email,United States,Los Angeles,California,90049,...,Gluten Free,TEC-AC-10003027,90.57,3,0,11.7741,NaT,2019-01-23,NaT,NaT
CA-2019-118255,45,2019-03-11,First Class,ON-18715,Odella Nelson,Sales,United States,Eagan,Minnesota,55122,...,Gluten Free,TEC-AC-10000171,45.98,2,0,19.7714,NaT,2019-03-13,NaT,NaT
CA-2019-118255,45,2019-03-11,First Class,ON-18715,Odella Nelson,Sales,United States,Eagan,Minnesota,55122,...,Gluten Free,TEC-AC-10000171,45.98,2,0,19.7714,NaT,2019-03-13,NaT,NaT
CA-2019-169194,48,2019-06-20,Standard Class,LH-16900,Lena Hernandez,Email,United States,Dover,Delaware,19901,...,Gluten Free,TEC-AC-10002167,45,3,0,4.95,NaT,2019-06-26,NaT,NaT

In [52]:
missing_in_campaign = set(orders["Order ID"]) - set(campaign["Order ID"])
missing_in_process  = set(orders["Order ID"]) - set(order_process["Order ID"])
missing_in_intern   = set(orders["Order ID"]) - set(intern_data["Order ID"])

print("Missing in Campaign:", len(missing_in_campaign))
print("Missing in Process:", len(missing_in_process))
print("Missing in Intern:", len(missing_in_intern))

Missing in Campaign: 4676
Missing in Process: 2007
Missing in Intern: 4805